{% extends "skeleton.phtml" %}

{# Codes in this section will be put between <head></head> tags. #}
{% block head %}
{% endblock %}

{# Part of title. Final title will be "CMS | {partOfTitle}" #}
{% block title %}Home{% endblock %}

{# The main content except head tabs. #}
{% block content %}
<h1>{{time}}</h1>
<a href="index/logout">Log out</a>
{% endblock %}

{# Codes in this section will be put after body content. #}
{% block script %}
{% endblock %}
