{% extends "skeleton.phtml" %}

{% block head %}
<link rel="stylesheet" href="css/login.css">
{% endblock %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<div class="simple-container">
    <form action="/cms/index/login" method="post" role="form">
      <div class="form-group">
        <label for="username">Username</label>
        <input type="text" class="form-control" id="username" size="32" placeholder="Enter username">
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" size="32" id="password" placeholder="Password">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form>
</div>
{% endblock %}

{% block script %}
{% endblock %}
