{% extends "skeleton.phtml" %}

{% block head %}
{% endblock %}

{% block title %}Good | new{% endblock %}

{% block content %}
<h1>New Good</h1>
<div class="simple-container">
    <form action="good/new" method="post" role="form">
        <div class="form-group">
            <label for="username">Name</label>
            <input class="form-control" placeholder="Please input name" type="text" id="name" name="name" value="{{obj.name}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Unit</label>
            <input class="form-control" placeholder="Please input unit" type="text" id="unit" name="unit" value="{{obj.unit}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Net Weight</label>
            <input class="form-control" placeholder="Please input net weight" type="text" id="netweight" name="netweight" value="{{obj.netweight}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Avg. Purchase Price</label>
            <input class="form-control" placeholder="Please input average purchase price" type="text" id="avginprice" name="avginprice" value="{{obj.avginprice}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Avg. Tax</label>
            <input class="form-control" placeholder="Please input average tax" type="text" id="avgtax" name="avgtax" value="{{obj.avgtax}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Avg. Postage</label>
            <input class="form-control" placeholder="Please input average postage" type="text" id="avgpostage" name="avgpostage" value="{{obj.avgpostage}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Selling Price</label>
            <input class="form-control" placeholder="Please input selling price" type="text" id="sellingprice" name="sellingprice" value="{{obj.sellingprice}}" size="32">
        </div>
        <div class="form-group">
            <label for="username">Type</label>
            <input class="form-control" placeholder="Please input type" type="text" id="type" name="type" value="{{obj.type}}" size="32">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-default">Submit</button>
            <a href="good" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

{% block script %}
{% endblock %}
